version: '3.7'
networks:
  component_net:
    driver: bridge
    external: true
services:
  go_dev:
    build: .
    image: service_go_dev_news
    container_name: service_dev_news
    restart: always
    networks:
      - component_net
    external_links:
      - mysql
      - redis
    ports:
      - '3001:3000'
    volumes:
      - ./src:/news
      - ./.air.toml:/www/.air.toml
      - ./conf:/www/conf
      -  /Users/miluyu/Documents/worker/logs/news_service:/news/logs