version: '3.7'
networks:
  component_net:
    driver: bridge
    external: true
services:
  news-api:
    build: 
      context: ../..
      dockerfile: ./deploy/dev/Dockerfile
    image: news-api
    container_name: news-api
    restart: always
    networks:
      - component_net
    external_links:
      - mysql
      - redis
    ports:
      - '3001:3000'
    volumes:
      - ../src:/news
      - ../.air.toml:/www/.air.toml
      - ../conf:/www/conf
      -  /Users/miluyu/Documents/worker/logs/news_service:/news/logs