version: '3.7'
networks:
  component_net:
    driver: bridge
    external: true
services:
  go:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    image: news_api
    container_name: news_api
    restart: always
    networks:
      - component_net
    external_links:
      - mysql
      - redis
    # ports:
    #   - '3000:3000'
    volumes:
      - /home/data/logs/news_service:/www/logs